import React from 'react';
import type { Metadata } from 'next';
import { Footer, Header } from '@/_components';
import { fontInter, fontMerriweather } from '@/config/fonts';
import { cn } from '@/lib/utils';
import { ApolloProvider } from '@apollo/client';
import client from '@/lib/apolloClient';
import './globals.css';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
    <body className={cn( fontInter.className, fontMerriweather.variable )}>
    <Header />
    <ApolloProvider client={client}>{children}</ApolloProvider>
    <Footer />
    </body>
    </html>
  );
}
