"use client";

import React from "react";
import "./globals.css";
import {Footer, Header} from "@/_components";
import {fontInter, fontMerriweather} from "@/config/fonts";
import {cn} from "@/lib/utils";
import {ApolloProvider} from "@apollo/client";
import createApolloClient from "@/lib/apollo";


const client = createApolloClient();

// import type {Metadata} from "next";
// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en" suppressHydrationWarning={true}>

        <body className={cn( fontInter.className, fontMerriweather.variable )}>
        <ApolloProvider client={client}>
            <Header/>
            {children}
            <Footer/>
        </ApolloProvider>
        </body>
        </html>
    );
}
