version: '3.8'

services:
  nextjs-app:
    image: node:18
    container_name: nextjs-app
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3001:3001'
    command: sh -c "npm install && npm run dev"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydatabase
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - '8080:8080'
    depends_on:
      - db

volumes:
  postgres_data:
